name: Feature request
description: Suggest an idea for this project
title: "[Feature Request / Suggestion]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        We appreciate your feedback on how to improve this project, please keep in mind this script is meant for EVERYONE'S 
        needs & not just your own. Prior to requesting a new feature, make sure it serve's a purpose for everyone &
        not just yourself / your project or it will be dismissed.
  - type: textarea
    id: Suggestion
    attributes:
      label: Suggestion / Feature Request
      description: Describe the feature(s) you would like to see added.
      placeholder: Tell us your suggestion
      value: "Your suggestion here"
    validations:
      required: true
 
